---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

### Human Cardiac Fibroblasts - optimize protocols:  
merge cardiac cells from different isolation protocols etc: [link](mergeHumanSamples.html)  
merge cardiac cells including samples from Graz: [link](mergeHumanSamplesPlusGraz.html)  
integrate  cardiac cells including samples from Graz: [link](integrateAcrossPatientsGZplusSG.html)  
assign labels to integrated data: [link](assignLabelshumanHeartsPlusGrazInt.html)  
integrate  cardiac cells including samples from Graz only subset with high Tcell fraction: [link](integrateAcrossPatientsGZplusSG_Subset.html)  
cw DE genes samples GRAZ and SG grouped by Tcell fraction: [link](DEgenesGZplusSG_Groups.html)  
vis sel DE genes samples GRAZ and SG grouped by Tcell fraction: [link](visHumanCardiacDEgenesGroups.html)  
cw DE genes samples GRAZ and SG subset on low Tcell fraction: [link](DEgenesGZplusSG_SubsetLT.html)  
cw DE genes samples GRAZ and SG subset on high Tcell fraction: [link](DEgenesGZplusSG_SubsetHT.html)  
cw DE genes iDCM versus other: [link](DEgenes_iDCM.html)  
visualize data for grand application with ECMO4: [link](Vis_plus_analyse_NormlaHFMyo.html)  
visualize data for grand application without ECMO4: [link](Vis_plus_analyse_NormlaHFMyo_woECMO4.html)  

