---
title: "Merge samples"
author: "Mechthild Lütge"
date: "14 May 2020"
output:
  html_document:
    self_contained: no
    code_folding: show
    number_sections: no
    toc: yes
    toc_depth: 3
    toc_float: true
    collapsed: no
    smooth_scroll: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, dev = c("png", "pdf"))
set.seed(1000)
```

## load packages
```{r libs}
suppressPackageStartupMessages({
  library(SingleCellExperiment)
  library(tidyverse)
  library(Seurat)
  library(magrittr)
  library(dplyr)
  library(purrr)
  library(ggplot2)
  library(here)
  library(runSeurat3)
  library(ggsci)
  library(ggpubr)
  library(pheatmap)
})

```

## set dir
```{r set dir}
basedir <- here()
metaDat <- read_tsv(paste0(basedir, "/metadata2.txt"), col_names = T)

```


## load and assign samples
```{r load plus assign samples}

assignSamples <- function(smpNam, basedirSmp, smpTec, smpID, smpCond, smpOri,
                          smpIso, smpProc){
  smpNamFull <- list.files(path = paste0(basedirSmp, "/data/humanFibroblast/"),
				 pattern = paste0(smpNam, ".*_seurat.rds"))
  seuratSmp <- readRDS(paste0(basedirSmp, "/data/humanFibroblast/", smpNamFull))
  seuratSmp$technique <- smpTec
  seuratSmp$ID <- smpID
  seuratSmp$cond <- smpCond
  seuratSmp$origin <- smpOri
  seuratSmp$isolation <- smpIso
  seuratSmp$processing <- smpProc
  return(seuratSmp)
}

####################################################################

for(i in 1:length(metaDat$Sample)){
  seuratX <- assignSamples(smpNam = metaDat$Sample[i],
                           basedirSmp = basedir,
                           smpTec = metaDat$technique[i],
                           smpID = metaDat$ID[i],
                           smpCond = metaDat$cond[i],
                           smpOri = metaDat$origin[i],
                           smpProc = metaDat$processing[i],
                           smpIso = metaDat$isolation[i])
  if(exists("seurat")){
    seurat <- merge(x = seurat, y = seuratX, project = "humanCardiacFibro")
  }else{
    seurat <- seuratX
  }
}

remove(seuratX)

```



## run clustering and DR 
```{r clustering and DR}

seurat <- NormalizeData(object = seurat)
seurat <- FindVariableFeatures(object = seurat)
seurat <- ScaleData(object = seurat, verbose = FALSE)
seurat <- RunPCA(object = seurat, npcs = 30, verbose = FALSE)
seurat <- RunTSNE(object = seurat, reduction = "pca", dims = 1:20)
seurat <- RunUMAP(object = seurat, reduction = "pca", dims = 1:20)
seurat <- FindNeighbors(object = seurat, reduction = "pca", 
        dims = 1:20)
res <- c(0.25,0.4,0.6)
for (i in 1:length(res)) {
        seurat <- FindClusters(object = seurat, resolution = res[i], 
            random.seed = 1234)
}

dat <- data.frame(table(seurat$dataset))
colnames(dat) <- c("dataset", "all")

knitr::kable(dat)

```


## color vectors
```{r colVec}

colPal <- c(pal_igv()(12),
            pal_aaas()(10))[1:length(levels(seurat))]
colTec <- pal_jama()(length(unique(seurat$technique)))
colSmp <- c(pal_uchicago()(9), pal_npg()(10), pal_aaas()(10), 
            pal_jama()(7))[1:length(unique(seurat$dataset))]
colCond <- pal_npg()(length(unique(seurat$cond)))
colID <- c(pal_jco()(10), pal_npg()(10), pal_futurama()(10),
           pal_d3()(10))[1:length(unique(seurat$ID))]
colOrig <- pal_aaas()(length(unique(seurat$origin)))
colIso <- pal_nejm()(length(unique(seurat$isolation)))
colProc <- pal_aaas()(length(unique(seurat$processing)))

names(colPal) <- levels(seurat)
names(colTec) <- unique(seurat$technique)
names(colSmp) <- unique(seurat$dataset)
names(colCond) <- unique(seurat$cond)
names(colID) <- unique(seurat$ID)
names(colOrig) <- unique(seurat$origin)
names(colIso) <- unique(seurat$isolation)
names(colProc) <- unique(seurat$processing)

```


## vis data {.tabset}
### clusters
```{r vis cluster}
DimPlot(seurat, reduction = "umap", cols=colPal)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```

### technique
```{r vis tecnique}

DimPlot(seurat, reduction = "umap", group.by = "technique", cols=colTec)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")

```


### Sample
```{r vis sample, fig.height=4, fig.width=9}

DimPlot(seurat, reduction = "umap", group.by = "dataset", cols=colSmp)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```

### ID
```{r vis ID}

DimPlot(seurat, reduction = "umap", group.by = "ID", cols=colID)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```


### Origin
```{r vis origin}

DimPlot(seurat, reduction = "umap", group.by = "origin", cols=colOrig)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```


### isolation
```{r vis isolation}

DimPlot(seurat, reduction = "umap", group.by = "isolation", cols=colIso)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```


### cond
```{r vis cond, fig.height=4, fig.width=5}

DimPlot(seurat, reduction = "umap", group.by = "cond", cols=colCond)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```

### processing
```{r vis proc}

DimPlot(seurat, reduction = "umap", group.by = "processing", cols=colProc)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```



## save objects
```{r save}
Idents(seurat) <- seurat$seurat_clusters
saveRDS(seurat, file = paste0(basedir, 
                              "/data/humanHeartsPlusGraz_merged_seurat.rds"))

```


## session info
```{r session info}
sessionInfo()
date()
```




